---
title: "Select images to print"
output: html_document
---

```{r message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glue)
library(magrittr)
library(stringr)
library(tidyverse)
```

## Prepare load_data 

```{r prepare_load_data, message=FALSE}
load_data <- 
  list.files("../load_data_csv/", pattern = "load_data.csv", full.names = T, recursive = T)  %>%
  map_df(read_csv)

convert_to_s3_url <- function(pathname, filename)  {
  file.path(
      str_replace(pathname, 
              "/home/ubuntu/bucket", 
              "https://s3.amazonaws.com/imaging-platform"),
      filename
  )
  
}

channels <- c("DNA", "ER", "RNA", "AGP", "Mito")

for (channel in channels) {
  url_sym <- rlang::sym(str_c("URL_Orig", channel))
  
  path_sym <- rlang::sym(str_c("PathName_Orig", channel))
   
  file_sym <- rlang::sym(str_c("FileName_Orig", channel))
   
  load_data %<>% 
    mutate(!!url_sym := convert_to_s3_url((!!path_sym), (!!file_sym)))
  
}

```

## Get metadata

```{r message=FALSE}
plates <- c("cmqtlpl1.5-31-2019-mt",
            "cmqtlpl261-2019-mt",
            "BR00106708",
            "BR00106709",
            "BR00107338",
            "BR00107339",
            "cmQTLplate7-2-27-20")

metadata <- 
  map_df(
    plates,
    function(plate) {
      read_csv(
        file.path("profiles", glue("{plate}_augmented.csv")),
        col_types = cols_only(
          Metadata_Plate = "c",
          Metadata_Well = "c",
          Metadata_Assay_Plate_Barcode = "c",
          Metadata_Plate_Map_Name = "c",
          Metadata_well_position = "c",
          Metadata_plating_density = "c",
          Metadata_line_ID = "c"
        )
      ) %>%
        distinct()
    }
  )


```

## Confirm that the plating density is the same across all lines

```{r}
metadata %>% distinct(Metadata_plating_density)
```


## Sample one well per cell line

```{r}
set.seed(5)

metadata_sampled <-
  metadata %>%
  group_by(Metadata_line_ID) %>%
  sample_n(1) %>%
  ungroup()
```

## Select a fixed field (a.k.a site)

```{r}
fieldID <- 5
```

## Select images to be printed

```{r}

filenames_header <- paste0("FileName_Orig", channels)

images <- 
  load_data %>%
  select(Metadata_Plate, Metadata_Well, Metadata_Row, Metadata_FieldID, matches("^URL_"), one_of(filenames_header)) %>%
  inner_join(metadata_sampled, by = c("Metadata_Plate", "Metadata_Well")) %>%
  filter(Metadata_FieldID == fieldID) %>%
  select(matches("^Metadata"), matches("^URL"), matches("^FileName_Orig"))
```


```{r}
images %>%
  select(matches("^URL_")) %>%
  gather(k, v) %>%
  select("v") %>%
  write_tsv("data/images_to_download.txt", col_names = FALSE)
```

```{sh}
#wget -i images_to_download.txt
```

```{r}
images %>%
  select(matches("^Metadata"),  matches("^FileName_Orig")) %>%
  write_csv("data/gwas_images.csv")
```

